### ISSUE TITLE
Tensorflow Lite - DataType error: DataType 9 is not recognized in Java

### ISSUE THREAD

**Issue by Whrothus** [xamarin/XamarinComponents#1079]
I am trying to use a object detection Tensorflow Lite

But When i run 

```
inputTensor = interpreter.GetInputTensor(0);
```
Error
```
Java.Lang.IllegalArgumentException: 'DataType error: DataType 9 is not recognized in Java (version 2.0.0)'
interpreter.RunForMultipleInputsOutputs(new Java.Lang.Object[] { input }, outputs);
java.lang.IllegalArgumentException: DataType error: DataType 9 is not recognized in Java (version 2.0.0)
 at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <8b3b636835d84984ba4604c1f57b1983>:0 
  at Xamarin.TensorFlow.Lite.Interpreter.RunForMultipleInputsOutputs (Java.Lang.Object[] inputs, System.Collections.Generic.IDictionary`2[TKey,TValue] outputs) [0x00043] in <4ff04480b90243d7b71dc70e02d1dbfb>:0 

	at org.tensorflow.lite.DataType.fromC(DataType.java:75)
	at org.tensorflow.lite.Tensor.<init>(Tensor.java:363)
	at org.tensorflow.lite.Tensor.fromIndex(Tensor.java:43)
	at org.tensorflow.lite.NativeInterpreterWrapper.getInputTensor(NativeInterpreterWrapper.java:293)
	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:136)
	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:311)

```
Following code:

```
var  outputTensor = interpreter.GetOutputTensor(0);
```

Is no problem

i did try a few other models they work but are toco
I use MLIR 

https://github.com/tensorflow/tensorflow/issues/41212 they use Java 2.4

I think its from
 https://github.com/tensorflow/tensorflow/blob/98a4bb7a39608275b90bcd221bc51103afadeb10/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Tensor.java#L351

Version update ?

**Comment by Whrothus** [comment]
Solved 
Just Use uint8 :D

converter.inference_input_type = tf.int8 
==>
converter.inference_input_type = tf.uint8

**Comment by moljac** [comment]
My preferred way: Please close the issue yourself if the problem is solved.

Thanks

**Comment by Whrothus** [comment]
This is NOT fixed i found a solution for me.
Solving it would be Updating the package or Checking when inserting model type if not to use int8 and giving feedback
For now it is a known issue or a Limitation on the package that the main TF supports. 

This might seem hard but thx for al the hard work moljac his is a good stuff you do great work

**Comment by micosacak** [comment]
TF version 1.13.1
Exception in thread "main" java.lang.IllegalArgumentException: DataType 20 is not recognized in Java (version 1.13.1)
	at org.tensorflow.DataType.fromC(DataType.java:85)
	at org.tensorflow.Tensor.fromHandle(Tensor.java:554)
	at org.tensorflow.Session$Runner.runHelper(Session.java:331)
	at org.tensorflow.Session$Runner.run(Session.java:264)
	at tftest2.main(tftest2.java:56)

I have similar problem.
What is DataType 20? I cannot find explanation for 20?

Here is my problem reported on; https://stackoverflow.com/questions/66654600/datatype-20-is-not-recognized-in-java-version-1-15-0

**Comment by micosacak** [comment]
System.out.println(inputTensor);
> FLOAT tensor with shape [1, 128, 128, 1]

as a result the tensor is (1,128,128,1) shape and float, which is correct!

**Comment by Whrothus** [comment]
@moljac 28 days 
@micosacak Are you doing image recognition ?

**Comment by micosacak** [comment]
Yes, I am doing image segmentation with Tensorflow. 

At the end I want to create a FiJi Plugin. That is why I start to write in Java.

**Comment by micosacak** [comment]
@Whrothus

**Comment by micosacak** [comment]
@Whrothus Do you have any suggestion?

**Comment by Whrothus** [comment]
Calm down make 1 comment Delete the other please 
You can solve this problem to not convert to FLOAT inputtensor [1, 128, 128, 1] (default) 
But To Byte input [1,128,128,3] 
when you do
converter = tf.lite.TFLiteConverter.from_saved_model(%yourModel%)
Add converter.inference_input_type = tf.uint8 
Like example.
[converter.txt](https://github.com/xamarin/XamarinComponents/files/6173271/converter.txt)

Now you got the right model


I am editing https://github.com/jacano/CameraTF  
My model SSD  [1,320,320,3] runs on my phone att 300ms/frame on real camera input 
(I will post my project when its done i am still tweaking)

**Comment by micosacak** [comment]
@Whrothus 

(1) As I normalize the input image for training (in range of 0.0-1.0 by dividing by 255), the image has to be float. As a result, tf.uint8 will not work? Or do I have to do training again without normalizing the data, in which the data format can be tf.uint8?

(2) I use a single channel as input, so the input shape has to be (None, 128, 128, 1) for the model. Can I still use Byte [1, 128, 128, 3]? There will be difference between the channel numbers?

(3) I am new with Java, it is quite different and challenging compared to Python.

**Comment by micosacak** [comment]
@Whrothus I created an example model and maven project and submitted it to this issue: (https://github.com/tensorflow/tensorflow/issues/41212). It can be downloaded from here as well [ReportProblem.zip](https://github.com/xamarin/XamarinComponents/files/6174848/ReportProblem.zip). 
I will appreciate if you could let me know, in case you can solve the problem.

**Comment by Whrothus** [comment]
@micosacak  This is a TF lite component so use that 
What I did was use a SSD to train a object detection (ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8)
(dataset from https://www.youtube.com/watch?v=Rgpfk6eYxJA&list=WL&index=34&t=1062s )
Converted that to TFlite 
And got 
![Screenshot_20210320_122240_com jacano cameratf](https://user-images.githubusercontent.com/26603923/111867951-99d63d00-8977-11eb-8601-dc9e56c1f7a3.jpg)
got a life camera input feat that +/- 200ms delay  on my Huawei P30lite (Small dataset +/- 8h training)
(This is what i got not using Emgu.TF.Lite)
You can change the detection to classification. 
This took me +/- 0.5 year in spare time to get it working (start learning Tensorflow to this) (you could do a lot faster)
Now i want to send generate new training records using the new images and telling them if they are not ok (Using FTP) (Hope it works)

This should be updated (my comment 19/2) but you need to use it the right way
Do you have a real dataset ? 
Good luck have fun.
