### ISSUE TITLE
FirebaseJobDispatcher Example doesn't build in VS2017. 

### ISSUE THREAD

**Issue by ericlee1974** [xamarin/XamarinComponents#367]
I get this error -

The "CreateLibraryResourceArchive" task failed unexpectedly.
Xamarin.Tools.Zip.ZipIOException: Error occured while reading ..\..\externals\firebase-dispatcher.aar
   at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options)
   at Xamarin.Android.Tasks.CreateLibraryResourceArchive.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Firebase.JobDispatcher

**Comment by newky2k** [comment]
Hi @ericlee1974,  I think that you may not be building the package via cake first.  This step downloads all of the necessary external files, including the aar files.  Once you do this it should make the relevant files available to the Xamarin solution and allow it to build.

Having said that though, there is a problem with running the cake.build script in that its not written to work on Windows so it will fail to complete(which if you are build via cake, would also explain the issue that you are having).    I have just create PR #410 to fix this side of it and i have tested this issue and the sample will now build and run.  I hoping that this will be merged today.

Thank you for your patience
