### ISSUE TITLE
 java.lang.ClassNotFoundException: Didn't find class   "com.crashlytics.android.Crashlytics" on path: DexPathList 

### ISSUE THREAD

**Issue by akankshajain00** [xamarin/XamarinComponents#518]
Hey,
I am using Xamarin.Android.Crashlytics 2.9.4.1 in my app and it's giving me this error. Can somebody help me solving this. I have also added dependencies -
Xamarin.Android.Crashlytics.Answers (>= 1.4.2)
Xamarin.Android.Fabric (>= 1.4.3)
Xamarin.Android.Crashlytics.Beta (>= 1.2.9)
Xamarin.Firebase.Core (>= 60.1142.1)
Xamarin.Build.Download (>= 0.4.11)

Caused by:   java.lang.ClassNotFoundException: Didn't find class   "com.crashlytics.android.Crashlytics" on path: DexPathList[[zip   file   "/data/app/com.anku.cin-qIa7I6dZgcWeWFzxDqSi5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.anku.cin-qIa7I6dZgcWeWFzxDqSi5Q==/lib/arm64,   /data/app/com.anku.cin-qIa7I6dZgcWeWFzxDqSi5Q==/base.apk!/lib/arm64-v8a,   /system/lib64, /system/vendor/lib64]]     at   dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)  at   java.lang.ClassLoader.loadClass(ClassLoader.java:312)              at   com.fivemobile.cineplex.MainActivity.n_onCreate(Native Method)             at   com.fivemobile.cineplex.MainActivity.onCreate(MainActivity.java:32)        at android.app.Activity.performCreate(Activity.java:7183)                at   android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)    at   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)  
--
java.lang.RuntimeException:   Unable to start activity   ComponentInfo{com.anku.cin/com.anku.cin.MainActivity}:   java.lang.ClassNotFoundException: Didn't find class   "com.crashlytics.android.Crashlytics" on path: DexPathList[[zip   file   "/data/app/com.fivemobile.cineplex-qIa7I6dZgcWeWFzxDqSi5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.fivemobile.cineplex-qIa7I6dZgcWeWFzxDqSi5Q==/lib/arm64,   /data/app/com.fivemobile.cineplex-qIa7I6dZgcWeWFzxDqSi5Q==/base.apk!/lib/arm64-v8a,   /system/lib64, /system/vendor/lib64]]     at   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)      at   android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)            at   android.app.ActivityThread.-wrap11(Unknown Source:0)               at   android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)             at   android.os.Handler.dispatchMessage(Handler.java:105)               at android.os.Looper.loop(Looper.java:164)    at   android.app.ActivityThread.main(ActivityThread.java:6938)         at java.lang.reflect.Method.invoke(Native   Method)        at   com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)          at   com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by newky2k** [comment]
@akankshajain00  Are you using proguard in your project?  do you get the same thing if you add it to a fresh Xamarin.Android project?

**Comment by akankshajain00** [comment]
No @newky2k I am not using proguard in my project. No for different project I am getting different error but this is something i could not able to resolve and stuck on this issue.

**Comment by newky2k** [comment]
@akankshajain00  could you please provide a small sample project with the issue so we can investigate

Thanks in advance

**Comment by tienhagioi** [comment]
same issue with unity 
[crash1.txt](https://github.com/xamarin/XamarinComponents/files/2858624/crash1.txt)
[crash2.txt](https://github.com/xamarin/XamarinComponents/files/2858629/crash2.txt)

**Comment by newky2k** [comment]
no response

**Comment by SathyaPanda** [comment]
I am also getting the same issue that @akankshajain00 has mentioned. Any updates on this. 

@akankshajain00  Please help me if you get any solution.

**Comment by Darrk** [comment]
I had the same issue and after downgrade of the Xamarin.Build.Download nuget from 0.10.0 to 0.8.0 error disappeared.
