### ISSUE TITLE
Running the interpreter successfully is not possible on Xamarin.TensorFlow.Lite 

### ISSUE THREAD

**Issue by h-maac** [xamarin/XamarinComponents#565]
Xamarin.TensorFlow.Lite.Interpreter Class has this signature;
```
[Register("runForMultipleInputsOutputs", "([Ljava/lang/Object;Ljava/util/Map;)V", "")]
        public void RunForMultipleInputsOutputs(Java.Lang.Object[] inputs, IDictionary<Integer, Java.Lang.Object> outputs);
```

It expects a `IDictionary<Integer,Java.Lang.Object>` as outputs, the value part of the dictionary is expected to be a `float[][][]` acording to the official [tensorflow android example](https://github.com/tensorflow/examples/blob/75f4d66acd84b67fbee073186c9e031db5513e34/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java#L178-L194).

the `float[]` or `Java.Lang.Float[]` can simply be casted to `Java.Lang.Object` but a Jagged Array is not a IJavaObject. and when a `float[]` is given as the `Dictionary.Value` exception is thrown and the output is as follows;

```
 UNHANDLED EXCEPTION:
 Java.Lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [10].
   at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <0ad2222fd7074badb5de547b1521aab0>:0 
   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00014] in <0ad2222fd7074badb5de547b1521aab0>:0 
   at Xamarin.TensorFlow.Lite.Interpreter.RunForMultipleInputsOutputs (Java.Lang.Object[] inputs, System.Collections.Generic.IDictionary`2[TKey,TValue] outputs) [0x00043] in <365817722dda4d7bb2782aa8813e5053>:0 
   at TFLDemo.ObjectDetection.TFLiteObjectDetectionAPIModel.recognizeImage (Android.Graphics.Bitmap bitmap) [0x0022d] in C:\hc\SchneiderImage\dotnet\TFLDemo\ObjectDetection\TFLiteObjectDetectionAPIModel.cs:221 
   at TFLDemo.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00049] in C:\hc\SchneiderImage\dotnet\TFLDemo\MainActivity.cs:32 
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <ad2f15102b3a4d36b40e9b0cbc11c376>:0 
   at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)
   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
 java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10, 4] and a Java object with shape [10].
 	at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:240)
 	at org.tensorflow.lite.Tensor.copyTo(Tensor.java:116)
 	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:152)
 	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:216)
 	at md5e90f53e366f80b4c76231dc7f1192891.MainActivity.n_onCreate(Native Method)
 	at md5e90f53e366f80b4c76231dc7f1192891.MainActivity.onCreate(MainActivity.java:29)
 	at android.app.Activity.performCreate(Activity.java:7326)
 	at android.app.Activity.performCreate(Activity.java:7317)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:6981)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

I am unsure if there is a workaround; a way to cast/convert a JaggedArray into a Java.Lang.Object but I could not find it.

and same thing applies to the Run method of the Interpreter. [Example Here](https://github.com/tensorflow/examples/blob/29f3cb71b31f32737907536a3ee9223a6970e68c/lite/examples/gesture_classification/android/app/src/main/java/org/tensorflow/lite/examples/gesture/ImageClassifierFloatInception.java#L99-L102)
```
 [Register("run", "(Ljava/lang/Object;Ljava/lang/Object;)V", "")]
        public void Run(Java.Lang.Object input, Java.Lang.Object output);
```

Here is a repository to quickstart and see the issue 
https://github.com/h-maac/Xamarin.Android.TensorFlow.Lite

**Comment by h-maac** [comment]
Apparently you can indeed do it, I have resolved it by using `Java.Lang.Object.FromArray()` & `Java.Lang.Object.ToArray<float[][]>()`. 
```
        public Java.Lang.Object OutputLocations
        {
            get => Java.Lang.Object.FromArray(outputLocations);
            set => outputLocations = value.ToArray<float[][]>();
        }
```

**Comment by newky2k** [comment]
resolved
