### ISSUE TITLE
SceneForm sample: Type com.google.ar.schemas.sceneform.LightingDef not present

### ISSUE THREAD

**Issue by craigktreasure** [xamarin/XamarinComponents#578]
I was just trying out the new SceneForm sample, but when trying to build HelloSceneForm, i get an `java.lang.TypeNotPresentException :  Type com.google.ar.schemas.sceneform.LightingDef not present` error. Am I missing something?

```
8>------ Build started: Project: HelloSceneForm, Configuration: Debug Any CPU ------
8>  HelloSceneForm -> G:\Repos\XamarinComponents\Android\SceneForm\samples\HelloSceneForm\bin\Debug\HelloSceneForm.dll
8>  Exception in thread "main" java.lang.TypeNotPresentException: Type com.google.ar.schemas.sceneform.LightingDef not present
8>  	at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
8>  	at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:54)
8>  	at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
8>  	at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
8>  	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toMethodHandle(LambdaDesugaring.java:599)
8>  	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toJvmMetatype(LambdaDesugaring.java:586)
8>  	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:401)
8>  	at org.objectweb.asm.ClassReader.a(Unknown Source)
8>  	at org.objectweb.asm.ClassReader.b(Unknown Source)
8>  	at org.objectweb.asm.ClassReader.accept(Unknown Source)
8>  	at org.objectweb.asm.ClassReader.accept(Unknown Source)
8>  	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
8>  	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
8>  	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
8>  	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
8>  Caused by: java.lang.ClassNotFoundException: Class com.google.ar.schemas.sceneform.LightingDef not found
8>  	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
8>  	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
8>  	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
8>  	at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)
8>  	... 14 more
8>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2525,3): error : java.lang.TypeNotPresentException :  Type com.google.ar.schemas.sceneform.LightingDef not present
========== Build: 7 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by chane1994** [comment]
I am getting the exact same error. Two weeks ago, I was able to get the project to build without this issue and now it is currently having the problem

**Comment by CodeGenie1** [comment]
Getting the same issue also. Some potential solution here :
https://stackoverflow.com/questions/54589632/xamarin-android-binding-invalid-opcode
https://github.com/xamarin/xamarin-android/commit/892a70050bd0614fc7cc97401880ffde5febde8c
One of the above mentions a fix in Visual Studio 2019, so don't know if anyone can confirm if this is working for 2019.

**Comment by newky2k** [comment]
@chane1994 @craigktreasure  could you please provide some details on you setup, and if possible upgrade to VS 2019 if you haven't done so already.  I had to do this when I was building the binding.

Regards

**Comment by craigktreasure** [comment]
Apologies for not providing those details earlier. I was using VS 2017 (15.9.11) on Windows. After switching to VS 2019 (16.1), it does appear to build successfully and the app works great. If this isn't expected to work in VS 2017, it might be good to add a readme with that info.

Thanks for the help!

**Comment by chane1994** [comment]
Thanks for the help, switch to VS2019 worked for me.
