### ISSUE TITLE
Xamarin.Build.TypeRedirector failes unexpectedly

### ISSUE THREAD

**Issue by mattleibow** [xamarin/XamarinComponents#783]
Occasionally in Visual Studio I'm getting this exception:

```
MSB4018	Xamarin.Forms.Platform.Android	The "RedirectMovedTypes" task failed unexpectedly.
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Xamarin.Build.TypeRedirector.RedirectMovedTypes.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	C:\Users\matthew\.nuget\packages\xamarin.build.typeredirector\0.1.1-preview\buildTransitive\Xamarin.Build.TypeRedirector.targets	12	
```

Testing on branch: https://github.com/xamarin/Xamarin.Forms/tree/cecil_matt_repro

**Comment by mattleibow** [comment]
Wait a sec, @PureWeen have you tried the latest: 0.1.2-preview

**Comment by PureWeen** [comment]
@mattleibow  I'm still seeing the exception after updating. I bumped the referenced branch up to the latest preview

Here's how I'm reproducing
- Build Embedding.XF manually
- Rebuild Embedding.Droid

If you don't see the exception then rebuild *Embedding.Droid* a couple times and it'll happen
