### ISSUE TITLE
Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.onResume()' on a null object reference

### ISSUE THREAD

**Issue by adelarsq** [xamarin/XamarinComponents#796]
Trying to start the [arcore sample](https://github.com/xamarin/XamarinComponents/tree/master/Android/ARCore/samples) gives this error on Visual Studio for Mac:

```
Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.onResume()' on a null object reference
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <af1c6fdcff1a4da4a0e44a8cdef352da>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <af1c6fdcff1a4da4a0e44a8cdef352da>:0
  at Android.Opengl.GLSurfaceView.OnResume () [0x0000a] in <a94a3bd35e1d47b586702ce8c8a1bd75>:0
  at HelloAR.MainActivity.OnResume () [0x0003d] in /Users/adelar/workspace/projects/game_pascoa/game_pascoa/tmp/XamarinComponents/Android/ARCore/samples/HelloAR/MainActivity.cs:123
  at Android.App.Activity.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <a94a3bd35e1d47b586702ce8c8a1bd75>:0
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.4(intptr,intptr)
  at java.lang.NullPointerException: Attempt to invoke virtual method 'void android.opengl.GLSurfaceView$GLThread.onResume()' on a null object reference
  at at android.opengl.GLSurfaceView.onResume(GLSurfaceView.java:591)
  at at crc643b96b0726de98615.MainActivity.n_onResume(Native Method)
  at at crc643b96b0726de98615.MainActivity.onResume(MainActivity.java:47)
  at at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
  at at android.app.Activity.performResume(Activity.java:7292)
  at at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
  at at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
  at at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
  at at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:193)
  at at android.app.ActivityThread.main(ActivityThread.java:6669)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Is there any setup that I'm missing?

**Comment by adelarsq** [comment]
Related https://github.com/Rajawali/Rajawali/issues/1971
