### ISSUE TITLE
ModelRenderable setSource exception

### ISSUE THREAD

**Issue by patrickvandewal** [xamarin/XamarinComponents#833]
Hello!

I'm currently trying to make a implementation with the SceneForm binding in Xamarin.Android and I am running into some trouble with getting the sample project up and running. After successfully being able to compile the binding and the sample project, the app crashes upon startup with the following exception:

```
Java.Lang.NoSuchMethodError: no non-static method "Lcom/google/ar/sceneform/rendering/ModelRenderable$Builder;.setSource(Landroid/content/Context;Landroid/net/Uri;)Ljava/lang/Object;"
```

And the full stacktrace:

```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NoSuchMethodError: no non-static method "Lcom/google/ar/sceneform/rendering/ModelRenderable$Builder;.setSource(Landroid/content/Context;Landroid/net/Uri;)Ljava/lang/Object;"
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <26521a5118b44c858c385715922b9d5d>:0 
[MonoDroid]   at Com.Kingscode.Template.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0003c] in /Users/patrickva04-21 14:03:27.102 I/MonoDroid(25865):   at Java.Interop.JniType.GetInstanceMethod (System.String name, System.String signature) [0x0000c] in <26521a5118b44c858c385715922b9d5d>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember) [0x00031] in <26521a5118b44c858c385715922b9d5d>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00006] in <26521a5118b44c858c385715922b9d5d>:0 
[MonoDroid]   at Google.AR.Sceneform.Rendering.ModelRenderable+Builder.SetSource (Android.Content.Context context, Android.Net.Uri sourceUri) [0x00053] in <e7d976a890b247818ef976959b28d9a3>:0 
[MonoDroid] 	at crc643c88d44abbfe9d67.Maindewal/Projects/citadel-template/Android/MainActivity.cs:50 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in /Users/runner/runners/2.165.0/work/1/s/xamarin-android/src/Mono.Android/obj/Release/android-29/mcw/Android.App.Activity.cs:2652 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.NoSuchMethodError stack trace ---
[MonoDroid] java.lang.NoSuchMethodError: no non-static method "Lcom/google/ar/sceneform/rendering/ModelRenderable$Builder;.setSource(Landroid/content/Context;Landroid/net/Uri;)Ljava/lang/Object;"
[MonoDroid] 	at crc643c88d44abbfe9d67.MainActivity.n_onCreate(Native Method)
[MonoDroid] 	at crc643c88d44abbfe9d67.MainActivity.onCreate(MainActivity.java:39)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7817)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7806)
[MonoDroid] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
[MonoDroid] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[MonoDroid] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:241)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7617)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```
Specifically, it seems it goes wrong in the binding itself.

```
[Register("setSource", "(Landroid/content/Context;I)Ljava/lang/Object;", "")]
public unsafe global::Google.AR.Sceneform.Rendering.ModelRenderable.Builder SetSource(global::Android.Content.Context context, int resource)
{
	const string __id = "setSource.(Landroid/content/Context;I)Ljava/lang/Object;";
	try
	{
		JniArgumentValue* __args = stackalloc JniArgumentValue[2];
		__args[0] = new JniArgumentValue((context == null) ? IntPtr.Zero : ((global::Java.Lang.Object)context).Handle);
		__args[1] = new JniArgumentValue(resource);
	 var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod(__id, this, __args); 
		return global::Java.Lang.Object.GetObject<global::Google.AR.Sceneform.Rendering.ModelRenderable.Builder>(__rm.Handle, JniHandleOwnership.TransferLocalRef);
	}
	finally
	{
	}
}
```

On this line:
```
	 var __rm = _members.InstanceMethods.InvokeAbstractObjectMethod(__id, this, __args); 
```

I've been trying to revert to a lower version of the package and the issue still persists. Also, I've been trying to run it on different versions of Android. I've been trying Nougat, Pie and 10. Without success!

Anyone has an idea of how to resolve this issue?

**Comment by lancefi** [comment]
Running into the same problem. Hopefully a fix or resolution to this will come about soon.

**Comment by NeuronKarrde** [comment]
Still no any workarounds?

**Comment by moljac** [comment]
managedReturn changed from:  
     `Google.AR.Sceneform.Rendering.ModelRenderable.Builder`
to
        `Java.Lang.Object`

```
Java.Lang.NoSuchMethodError: no non-static method "Lcom/google/ar/sceneform/rendering/ModelRenderable$Builder;.setSource(Landroid/content/Context;Landroid/net/Uri;)Ljava/lang/Object;"
```

PR: https://github.com/xamarin/XamarinComponents/pull/883

**Comment by TomBruyneel** [comment]
It doesn't look like the fix works, have you tested this yourself?

**Comment by TomBruyneel** [comment]
I got it working by changing metadata.xml to:

```xml
<metadata>


  <attr path="/api/package[@name='com.google.ar.sceneform.rendering']" name="managedName">Google.AR.Sceneform.Rendering</attr>

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='makeRenderable' and count(parameter)=0]" />

  <attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ViewRenderable']/method[@name='makeCopy' and count(parameter)=0]" name="return">Google.AR.Sceneform.Rendering.Renderable</attr>
  <attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ModelRenderable']/method[@name='makeCopy' and count(parameter)=0]" name="return">Google.AR.Sceneform.Rendering.Renderable</attr>

  <!--<attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='android.net.Uri']]" name="return">Java.Lang.Object</attr>   
    <attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='java.util.concurrent.Callable&lt;java.io.InputStream&gt;']]" name="return">Java.Lang.Object</attr>
    <attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=1 and parameter[1][@type='com.google.ar.sceneform.rendering.RenderableDefinition']]" name="return">Java.Lang.Object</attr>-->

  <!--<remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='android.net.Uri']]" />
  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='java.util.concurrent.Callable&lt;java.io.InputStream&gt;']]" />
  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=1 and parameter[1][@type='com.google.ar.sceneform.rendering.RenderableDefinition']]" />
  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='int']]" />-->

  <!--<attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setSource' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='int']]" name="return">Java.Lang.Object</attr>-->

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ModelRenderable.Builder']/method[@name='setSource']" />

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ViewRenderable.Builder']/method[@name='setSource']" />

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='getSelf' and count(parameter)=0]" />


  <attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='setRegistryId' and count(parameter)=1 and parameter[1][@type='java.lang.Object']]" name="return">Java.Lang.Object</attr>

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ViewRenderable.Builder']/method[@name='makeRenderable' and @return='com.google.ar.sceneform.rendering.ViewRenderable' and count(parameter)=0]" />
  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ModelRenderable.Builder']/method[@name='makeRenderable' and @return='com.google.ar.sceneform.rendering.ModelRenderable' and count(parameter)=0]" />

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/interface[@name='Light.LightChangedListener']" />

  <attr path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ModelRenderable']/method[@name='makeCopy' and count(parameter)=0]" name="final">true</attr>

  <!--<remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='ViewRenderable.Builder']/method[@name='build' and count(parameter)=0]" />-->

  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='build' and count(parameter)=0]" />
  <remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='getRenderableClass' and count(parameter)=0]" />

  <attr
        path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='EnvironmentalHdrLightEstimate.CubeMapImage']"
        name="visibility"
        >
    public
  </attr>
  <attr
      path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']"
      name="visibility"
        >
    public
  </attr>
</metadata>
```

and uncommenting all the lines in ModelRenderableBuilder and ViewRenderableBuilder

**Comment by lingo100** [comment]
@TomBruyneel
I did what you suggested in metadata.xml, but still got the same error at runtime:

**Java.Lang.IncompatibleClassChangeError:** 'no non-static method "Lcom/google/ar/sceneform/rendering/ModelRenderable$Builder;.setSource(Landroid/content/Context;Ljava/util/concurrent/Callable;)Ljava/lang/Object;"'

Does anyone have a working sample?

**Comment by Siscomatias** [comment]
Any news on this? still having the same issue

**Comment by moljac** [comment]
Please try adding proguard rule[s]. From top of my head something like:

```
-keep public class com.google.ar.sceneform.rendering.ModelRenderable { *; }
-keep public class com.google.ar.sceneform.rendering.ModelRenderable.Builder { *; }
```

and please report if that helps.

**Comment by moljac** [comment]
After adding proguard rules and fixing metadata according to @TomBruyneel's tips -  I made few steps further.

Now there are Filament errors:

```
[Filament] Panic
[Filament] in static filament::MaterialParser *filament::details::FMaterial::createParser(backend::Backend, const void *, size_t):487
[Filament] reason: Material version mismatch. Expected 4 but received 3.
[Filament] 
[libc] Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 25360 (.hellosceneform), pid 25360 (.hellosceneform)
```

and according to:

https://github.com/google-ar/sceneform-android-sdk/issues/866

this points to errors in `sfa` and/or `sfb` files.

**Comment by refusal** [comment]
it works for me. Also, something wrong with the andy.sfb. Try the sfb file from the attachments.

```
var builder = ModelRenderable.InvokeBuilder();
var javaClass = Java.Lang.Class.FromType(builder.GetType());
var methods = javaClass.GetMethods();
var method = methods[11]; // setSource method
method.Invoke(builder, this, Resource.Raw.fox_face);
builder.Build(FinishLoading);

private void FinishLoading(ModelRenderable model)
{
   andyRenderable = model;
   arFragment.TapArPlane += OnTapArPlane;
}
```
[fox_face.sfb.zip](https://github.com/xamarin/XamarinComponents/files/6561312/fox_face.sfb.zip)

**Comment by miki-bgd** [comment]
I am using this workaround (similar to what @refusal suggested):
(**path** is .sfb file relative path in the **Assets** folder, activity is MainActivity)
``` cs
public async Task<Node> Load(string path)
{
    var builder = ModelRenderable.InvokeBuilder();
    var javaClass = Java.Lang.Class.FromType(builder.GetType());
    var method = javaClass.GetMethod("setSource",
        Java.Lang.Class.FromType(typeof(global::Android.Content.Context)),
        Java.Lang.Class.FromType(typeof(Android.Net.Uri))
    );
    method.Invoke(builder, activity, Android.Net.Uri.Parse(path));
    
    // Task helps to continue only when model is finished loading.
    Task t = new Task(() => { });
    Node n = new Node();
    builder.Build(renderable =>
    {
        n.Renderable = renderable;
        t.Start();
    });
    await t;
    return n;
}
```


PS. However, thanks **refusal** for showing the way with accessing methods by index, i completely forgot on that. It helped me use another **setSource** method (for .glb files) very fast.

PS2. For anyone interested in .glb/.gltf:
```cs
private async Task<Node> LoadGlb(string path)
{
    var builder = ModelRenderable.InvokeBuilder();
    var javaClass = Java.Lang.Class.FromType(builder.GetType());

    var methods = javaClass.GetMethods();
    var model = RenderableSource
        .InvokeBuilder()
        .SetSource(activity, Android.Net.Uri.Parse(path), RenderableSource.SourceType.Glb) // Or .gltf
        .Build();
    var method = methods[13];
    method.Invoke(builder, activity, model);
    
    Node n = new Node()
    {
	LocalPosition = new Google.AR.Sceneform.Math.Vector3(0, 0, 0)
    };
    // Task helps to continue only when model is finished loading.
    Task t = new Task(() => { });
    builder.Build(renderable =>
    {
        n.Renderable = renderable;
        t.Start();
    });
    await t;
    return n;
}

```

**Comment by prabakaranr** [comment]
[miki-bgd](https://github.com/miki-bgd) thanks for posting the code to load the glb, the app is crashing immediately after finding the plane, is the same code work with the latest version of AR packages?

This is the error I am always noticing from the Logcat
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x72f79faff8 in tid 26071 (AsyncTask #2), pid 26025 (.hellosceneform)
