### ISSUE TITLE
NotificationHubsSampleAndroid will not compile  File ..\externals\notificationhubs.aar does not exist and file creation wasn't requested

### ISSUE THREAD

**Issue by donaldashworth** [xamarin/XamarinComponents#922]
XACLR7024	Xamarin.Tools.Zip.ZipIOException: File ..\externals\notificationhubs.aar does not exist and file creation wasn't requested
   at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options) in /Users/runner/runners/2.165.0/work/1/s/ZipArchive.cs:line 273
   at Xamarin.Android.Tasks.CreateLibraryResourceArchive.RunTask()
   at Xamarin.Android.Tasks.AndroidTask.Execute()	Xamarin.Azure.NotificationHubs.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Bindings.targets	505

**Comment by mattpodwysocki** [comment]
@donaldashworth this requires you to have cake installed and run the cake build for the component
